version: "3"
services:

  traefik:
    image: traefik:raclette
    ##image: traefik:morbier
    command: -c /dev/null --web --docker --docker.swarmmode --docker.watch --docker.domain=test.com --logLevel=DEBUG
    depends_on:
      - app
      - www
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 88:80
      - 8080:8080
    networks:
      - frontend
    deploy:
      placement:
        constraints: [node.role == manager]
  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    networks:
      - frontend
    deploy:
      placement:
        constraints: [node.role == manager]
  app:
    image: nouchka/dockercloud-hello-world:latest
    networks:
      - frontend
    depends_on:
      - redis
    deploy:
      labels:
        - traefik.port=80
        - traefik.frontend.rule=Host:app.test.com
      replicas: 8
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure
  www:
    image: dockercloud/hello-world:latest
    networks:
      - frontend
    deploy:
      labels:
        - traefik.port=80
        - traefik.frontend.rule=Host:www.test.com
      replicas: 4
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure

networks:
  frontend:

volumes:
  redis-data:
