version: "3"
services:

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    networks:
      - frontend
    deploy:
      placement:
        constraints: [node.role == manager]
  vote:
    image: nouchka/dockercloud-hello-world:latest
    ports:
      - 5000:80
    networks:
      - frontend
    depends_on:
      - redis
    deploy:
      replicas: 6
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure

networks:
  frontend:

volumes:
  redis-data:
